baseurl = "https://www.dennisacar.de"
title = "Dennis Acar"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
  author = "Dennis Acar"
  info = "IT-Consultant & Software-Engineer"
  description = "Dennis Acar's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  #footercontent = "Enter a text here."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorScheme = "light"
  hidecolorschemetoggle = true

  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/dacbreakpoint/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/dennis-acar/"
[[params.social]]
  name = "Xing"
  icon = "fa fa-xing fa-2x"
  weight = 3
  url = "https://www.xing.com/profile/Dennis_Acar"

# Menu links
#[[menu.main]]
#  name = "About"
#  weight = 1
#  url = "about/"
#[[menu.main]]
# name = "Blog"
#  weight = 2
#  url  = "posts/"
#[[menu.main]]
#  name = "Tools"
#  weight = 3
#  url = "tools/"
